apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx-deployment
  labels:
    app:  nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-deployment
  replicas: 3
  strategy: {}
  template:
    metadata:
      labels:
        app:  nginx-deployment
    spec:
      containers:
      - name:  nginx
        image:  nginx:1.19.2
        resources:
          requests:
            cpu: "0.25"
            memory: 50Mi
          limits:
            cpu: "0.5"
            memory: 100Mi
        ports:
        - containerPort:  80
          name: http
      restartPolicy: Always